/**
 * @deprecated This file is deprecated. Use src/domain/onsen/types.ts instead.
 * 
 * Onsen Theme Extension Types (Legacy)
 * 
 * This file is kept for backward compatibility but should not be used in new code.
 * Migrate to src/domain/onsen/types.ts for new implementations.
 */

// Re-export from new structure for backward compatibility
export type {
  OnsenRegion,
  OnsenInfo,
  OnsenAccess,
  OnsenAccommodation,
  OnsenContent,
} from '../../src/domain/onsen/types';

// Legacy types that may still be referenced
import { DocPage } from './theme-types';
import { OnsenSpot as NewOnsenSpot } from '../../src/domain/onsen/types';

/**
 * @deprecated Use OnsenSpot from src/domain/onsen/types instead
 */
export type OnsenSpot = NewOnsenSpot;

/**
 * @deprecated Use OnsenImageSlots from src/domain/onsen/types instead
 * 古い形式との互換性のため、OnsenImagesという名前で再エクスポート
 */
export type { OnsenImageSlots as OnsenImages } from '../../src/domain/onsen/types';

/**
 * @deprecated Use OnsenMeta from src/domain/onsen/types instead
 */
export interface OnsenMeta {
  priority: number;
  tags: string[];
  related: string[];
  publishedAt: string;
  updatedAt: string;
  isAutoGenerated?: boolean;
}

/**
 * Doc page with onsen extension
 */
export interface OnsenDocPage extends DocPage {
  onsen?: OnsenSpot;
}

/**
 * Check if a page is an onsen page
 */
export function isOnsenDoc(page: any): page is OnsenDocPage {
  return page && typeof page === 'object' && 'onsen' in page;
}
