import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getAreaForOnsen, getOnsen, getOnsens, getPurposes, getRelatedOnsens, getSiteData } from '../../lib/onsen-site';
import { ImageCredit } from '../../components/site/ImageCredit';
import { OnsenCard } from '../../components/site/OnsenCard';
import { OnsenGallery } from '../../components/site/OnsenGallery';
import { DayTripInfo } from '../../components/site/DayTripInfo';
import { getOnsenMedia } from '../../lib/onsen-media';
import { getOnsenDetailedGuide } from '../../lib/onsen-guides';
import { OnsenDetailedGuide } from '../../components/site/OnsenDetailedGuide';

interface Props { params: Promise<{ slug: string }> }
export function generateStaticParams() { return getOnsens().map((onsen) => ({ slug: onsen.slug })); }
export async function generateMetadata({ params }: Props) { const { slug } = await params; const onsen = getOnsen(slug); const data = getSiteData(); if (!onsen) return { title: '温泉が見つかりません' }; const media = getOnsenMedia(onsen); return { title: `${onsen.name} | 関東湯旅案内`, description: `${onsen.catchcopy} ${onsen.summary}`, openGraph: { title: `${onsen.name} | ${data.site.name}`, description: onsen.summary, ...(media.hero ? { images: [{ url: media.hero.src, width: 1200, height: 630, alt: media.hero.alt }] } : {}) } }; }

export default async function OnsenDetailPage({ params }: Props) {
  const { slug } = await params; const onsen = getOnsen(slug); if (!onsen) notFound();
  const area = getAreaForOnsen(onsen); const purposes = getPurposes(); const related = getRelatedOnsens(onsen.slug, 3); const matchedPurposes = purposes.filter((purpose) => onsen.useCases.includes(purpose.id)); const media = getOnsenMedia(onsen); const detailedGuide = getOnsenDetailedGuide(onsen.slug); const hasDisplayImage = Boolean(media.hero);
  return (
    <main className="bg-[#f6f0e5] text-[#2e261f]">
      <section className="relative overflow-hidden bg-[#241b15] text-white"><div className="absolute inset-0">{media.hero ? <Image src={media.hero.src} alt={media.hero.alt} fill priority sizes="100vw" className="object-cover opacity-60" /> : <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(239,208,146,0.28),transparent_28%),linear-gradient(135deg,#31565a,#1f302e_55%,#4b3829)]" aria-hidden="true" />}<div className="absolute inset-0 bg-[linear-gradient(115deg,#201710_5%,rgba(36,27,21,0.88)_45%,rgba(36,27,21,0.3)_100%)]" /></div><div className="relative mx-auto flex min-h-[70vh] max-w-7xl flex-col justify-end px-5 pb-14 pt-24 md:px-8 md:pb-20"><Link href="/onsens" className="portal-button-light mb-10 w-fit">← 温泉一覧へ戻る</Link><p className="text-sm font-bold tracking-[0.28em] text-[#f2d596]">{onsen.prefecture}{area ? ` / ${area.name}` : ''}</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-bold leading-tight md:text-7xl">{onsen.name}</h1><p className="mt-6 max-w-2xl text-xl font-semibold leading-9 text-[#fffaf0]">{onsen.catchcopy}</p><div className="mt-8 flex flex-wrap gap-2">{matchedPurposes.map((purpose) => <span key={purpose.id} className="rounded-full bg-[#f2d596] px-4 py-2 text-sm font-bold text-[#2e2117]">{purpose.shortLabel}</span>)}{onsen.tags.map((tag) => <span key={tag} className="rounded-full border border-white/35 bg-white/10 px-4 py-2 text-sm font-semibold text-white">{tag}</span>)}</div><div className="mt-8">{media.hero ? <ImageCredit image={media.hero} /> : <p className="text-xs font-semibold text-[#f2d596]">この施設の写真は、対象とライセンスを確認したうえで掲載します。</p>}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-12 md:px-8 md:py-20"><div className="grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:items-start">{hasDisplayImage ? <OnsenGallery images={media.gallery} name={onsen.name} /> : <div className="grid min-h-[300px] place-items-center rounded-[1.5rem] border border-[#d8c8ae] bg-[#fffaf0] p-8 text-center"><div><p className="eyebrow">IMAGE REVIEW</p><p className="mt-3 font-serif text-3xl font-bold text-[#33291f]">写真を確認・差し替え中です</p><p className="mt-4 max-w-md text-sm leading-7 text-[#66594d]">施設・温泉地と一致し、ライセンスを確認できる画像だけを掲載します。</p></div></div>}<aside className="space-y-5"><div className="rounded-[2rem] border border-[#d8c8ae] bg-[#fffaf0] p-6 shadow-[0_12px_35px_rgba(74,55,35,0.08)]"><p className="eyebrow">PLAN YOUR VISIT</p><h2 className="mt-3 font-serif text-3xl font-bold text-[#33291f]">この湯へ行く準備</h2><p className="mt-4 text-sm leading-7 text-[#66594d]">営業時間・料金・休館日・交通は変わるため、訪問前に公式情報を確認してください。</p><div className="mt-6 grid gap-3"><Link href={onsen.officialUrl} target="_blank" rel="noopener noreferrer" className="portal-button-primary">{onsen.officialName}へ</Link><Link href={onsen.mapUrl} target="_blank" rel="noopener noreferrer" className="portal-button-secondary">Googleマップで行き方を見る</Link></div><p className="mt-4 text-xs font-semibold text-[#76624f]">情報確認日: {onsen.verifiedAt}</p></div><div className="rounded-[2rem] border border-[#d8c8ae] bg-white p-6"><p className="eyebrow">BASIC DATA</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="font-bold text-[#8c6846]">泉質</dt><dd className="mt-2 flex flex-wrap gap-2">{onsen.springTypes.map((type) => <span key={type} className="rounded-full bg-[#f1e3c7] px-3 py-1 text-xs font-bold text-[#5a4027]">{type}</span>)}</dd></div><div><dt className="font-bold text-[#8c6846]">エリア</dt><dd className="mt-1 font-semibold text-[#33291f]">{area?.name ?? onsen.areaId}</dd></div><div><dt className="font-bold text-[#8c6846]">アクセス</dt><dd className="mt-1 leading-6 text-[#4b4036]">{onsen.access}</dd></div></dl></div></aside></div></section>

      <section className="bg-[#fffaf0] py-16 md:py-24"><div className="mx-auto grid max-w-7xl gap-8 px-5 md:grid-cols-[0.85fr_1.15fr] md:px-8"><div><p className="eyebrow">WHY GO</p><h2 className="mt-4 font-serif text-4xl font-bold text-[#33291f] md:text-5xl">ここでしか味わえない<br />湯旅の理由</h2><p className="mt-5 text-base leading-8 text-[#66594d]">{onsen.summary}</p></div><div className="grid gap-4 sm:grid-cols-2">{onsen.features.map((feature) => <div key={feature} className="rounded-[1.5rem] border border-[#d8c8ae] bg-white p-5"><span className="text-2xl text-[#b77c38]">♨</span><p className="mt-3 text-sm font-bold leading-7 text-[#4b4036]">{feature}</p></div>)}</div></div></section>

      <section className="bg-[#24444a] py-16 text-white md:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-[0.85fr_1.15fr] md:px-8"><div><p className="text-sm font-bold tracking-[0.24em] text-[#f2d596]">SPRING & EXPERIENCE</p><h2 className="mt-4 font-serif text-4xl font-bold md:text-5xl">泉質を知ると、<br />湯めぐりが深くなる</h2><p className="mt-5 text-sm leading-7 text-[#dce6e2]">適応症は泉質や入浴条件によって異なります。ここでは旅の計画に役立つ一般的な特徴を紹介しています。</p></div><div className="space-y-4">{onsen.benefits.map((benefit) => <div key={benefit.label} className="rounded-2xl border border-white/15 bg-white/10 p-5"><p className="font-serif text-2xl font-bold text-[#f2d596]">{benefit.label}</p><p className="mt-2 text-sm leading-7 text-[#f6fbf8]">{benefit.text}</p></div>)}<p className="text-xs leading-6 text-[#c9d7d3]">{onsen.editorialNote}</p></div></div></section>

      <section className="bg-[#f6f0e5] py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10"><p className="eyebrow">SEASONAL GUIDE</p><h2 className="mt-4 font-serif text-4xl font-bold text-[#33291f] md:text-5xl">季節で変わる、行きたい理由</h2></div><div className="grid gap-4 md:grid-cols-3">{onsen.seasonal.map((item) => <div key={item.season} className="rounded-[1.5rem] border border-[#d8c8ae] bg-[#fffaf0] p-6"><p className="font-serif text-3xl font-bold text-[#8a5b2b]">{item.season}</p><p className="mt-4 text-sm leading-7 text-[#4b4036]">{item.text}</p></div>)}</div></div></section>

      <OnsenDetailedGuide guide={detailedGuide} />
      <DayTripInfo info={onsen.dayTrip} />
      <section className="bg-white py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10"><p className="eyebrow">STAY & DAY TRIP</p><h2 className="mt-4 font-serif text-4xl font-bold text-[#33291f] md:text-5xl">宿泊・日帰り施設を探す</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#66594d]">施設ごとに営業日・入浴条件が異なります。公式案内が確認できる施設は公式情報と地図を、確認できない候補は地図を開いて最新情報を確認してください。</p></div><div className="grid gap-4 md:grid-cols-3">{onsen.facilities.map((facility) => <div key={facility.name} className="rounded-[1.5rem] border border-[#d8c8ae] bg-[#fffaf0] p-5"><p className="text-xs font-bold tracking-[0.14em] text-[#8c6846]">{facility.kind}</p><h3 className="mt-3 min-h-12 text-base font-bold leading-6 text-[#33291f]">{facility.name}</h3><div className="mt-5 grid gap-2">{facility.url !== facility.mapUrl && <Link href={facility.url} target="_blank" rel="noopener noreferrer" className="portal-button-secondary">施設案内を開く</Link>}<Link href={facility.mapUrl} target="_blank" rel="noopener noreferrer" className="portal-button-outline">地図で見る</Link></div></div>)}</div></div></section>

      <section className="bg-[#f6f0e5] py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10"><p className="eyebrow">MORE JOURNEYS</p><h2 className="mt-4 font-serif text-4xl font-bold text-[#33291f] md:text-5xl">次に行きたい温泉</h2></div><div className="grid gap-8 md:grid-cols-3">{related.map((item) => <OnsenCard key={item.slug} onsen={item} area={getAreaForOnsen(item)} purposes={purposes} />)}</div></div></section>
    </main>
  );
}
